[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "4c6673b5f65a0516b5eaab2e35fb9bbaa8b2c1dd"
os = "macos"

    [[ADOLC.download]]
    sha256 = "0d277e8fbee28ff16a5582837cf0dca9db39656cd0981db23f67089fa488c0f9"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "dee5b3588fe854aa75ec45d7f98cbef941e7ba5d"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d9b1dbccdf10f41af8399b21294f8976ab06976875c7c2a1f73aaee545282309"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54f0a12b1c891f97c1b37afe9a3a0a311ad6de12"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "028ce8ab8188e59d21fc4a2d112d5a6a2ae2d96e4aa3c657c83df0a99867bd94"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "973fa4034b9d880ab090286afe49f630138c71cf"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "d2813282a668551cb8ad3c32e1e80df81f6f917baa06e6cc43849b6f62cdefa7"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "b09ef177f4dee7545d57c758aa1abdc5ff0a4229"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b2382c8e0e1779bb5125187d509e644581849b37dd7976e7c0c59d9657a43d5c"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-linux-gnu.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "49c4d5ac49a704672d6177ed3e6a338a60b5a0e6"
os = "windows"

    [[ADOLC.download]]
    sha256 = "aced6c20b90a1e4e9bbce524de4448bb64efb7e1f92fc87a67a2d62415544e24"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
git-tree-sha1 = "549484f270c8d3a498aed52ba5a45da33176c128"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "0ae9c5afeb3089dc12b7dd09fca2b4cae27720c0d17ce2f2ac845723e58e471f"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "078a22620625e9433d398b4bd789a6568784fa15"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "f2ac25645a2b685486a92ada2ac43b3d883ca71b14ac24222a5279fb4f830fee"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "3c154936c8c8a11ce2a2521c998ac4ee855b7584"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "a935f8f5963f84930d6317867dc724b7488b0f9f34d2a9212f2fc8d7f987afbb"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-musl.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "a2b97bf345a7876940e3c7753a5587b466b25b2e"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "b5db04953e7abd2640563ecfd44adbeb8ef42f53252d6c0985f69839d76c1945"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "168941c3100f1288e197b4d10bf94089e6911445"
os = "windows"

    [[ADOLC.download]]
    sha256 = "c9491fccf5d732b2bab9a5d19359dcec3d5dde94ff573ce1b7741dee3a45d953"
    url = "https://github.com/TimSiebert1/ADOLC2_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "da4b5bd11c3b0c458c52f8a58422ec73f169a79e"
os = "macos"

    [[ADOLC.download]]
    sha256 = "7fd27b328bac3d5d9ed0162e44f38686be1d23e629d2ec80fa862da1bb7a9936"
    url = "https://github.com/local/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-apple-darwin.tar.gz"
