[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "180b2fe412ad564ad2ced0aa12c41c24a1476935"
os = "macos"

    [[ADOLC.download]]
    sha256 = "352a23a42a0774e1fd32744a4a673fd90ce6a8a9c95d76d9b9412679d96c4fe9"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "63a06750f3fc21850bedf8bc0fae6ff261a5e6f4"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8f0d2ada0e06f3aabcec0222d6082dc9cf5fac2c0fd0722389d5349d47bfce2e"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0e0533489d723284c2b08aece734c8e4ae421ff9"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "8c6fe86e0aa4203077d91c5844663b7d291f9ca452ea4f268c1916ab3360429f"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d0ac6d19794a36c841783e215645c28ed584f1e"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ea471688dd3350cd104f98ecdbb28775fde627f8af1f7a83e1c8d2b3fccb25c4"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "ef216a29e4b7a55a97a8b8ef2041add73ccf040d"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "bdc37adea8b63bc4cf67c0ec7097e609770c0b8412edd18c81e230376de656a1"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-linux-gnu.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "db770b78f0e2e90d38ddabed158ec3517852b012"
os = "windows"

    [[ADOLC.download]]
    sha256 = "43f4e4e59c32fa0e737ac3b19a63b56d94c78bd85e48dc323241b882eb22b843"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
git-tree-sha1 = "b7b3e9ed89ab7040439146396ed28eb5bb5b1116"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "e38c6ff0db7638bc9c2265ba421ef55c60d11f2c06058782ce019e53bcf6c3cd"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "5eeed8a033906cdc383bd2993728da172c76ca4b"
os = "macos"

    [[ADOLC.download]]
    sha256 = "84c6e542c2507da39de91827be604c13905ff19948c8a627532fd4c71c9fa773"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "d42a53528abd90cea895ddfa57b772ce51048957"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "474b1c99a4a0607eebe770d27b6bf31b84c5bb810260d8630e84c5f8b98c239f"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "ceeb7e42da7b0a209e832d09133761a56c34a185"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "cc1669780f34bf55ded7b98d2645742fee6b2177aecca3f6bb3ade85687ba440"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-musl.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "5636232fd30738cfaee8e25d944705a761b3f28c"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "1491605fdb737ad1e44ffb9f5def6b1431b97fe11e09af08cfabf5dc37af9388"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "23797f8ee815554dd0e9f0371a4ed62c909b4e3b"
os = "windows"

    [[ADOLC.download]]
    sha256 = "1295b7575e9d92c368014e3a3fecac4b5b8b7dcea92739c5017c39ffa2eb89ec"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-w64-mingw32.tar.gz"
