[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "c6fb7f77a1ac923fcf8237d954b652e4cbd70647"
os = "macos"

    [[ADOLC.download]]
    sha256 = "6012f3cd732716cebcf6a4420e1b2acf68e73037a15b32331014f4589c71bef8"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.aarch64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "cf2eee3f0c884e884a9244a9832a70ee96c29f53"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9666840d287e381266ad52918df3dde03b654a9ec438a08255d670dfbc4e2e4b"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.aarch64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fba7c6808ef62532ff89cf9017eabc97cad87c53"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "bb67edcf9cf5d6cd6f03ae5deeba8fd719338d052759f275dcfb147db054973f"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.armv6l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ea69472e92e209f697ed8a54db3010ec58b4788"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "38c4fcfd5278ab7b00220420e0e0c4911c8a593cb63f7e2d71dc05e292452dbb"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.armv7l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "80fdf7bca006b45bc5560306d3b0a458ad3f069f"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "ca629806788abaadc9c4ee401ee4f2dbee9a8a7a72542286362cca628c9af4aa"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.i686-linux-gnu.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "9f5b50d147035269ff71b97e250f5a1722b4063e"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4209d0d7a8dc94288843bf18bff9ccc40b27c15a890f97059552d0f599875d7c"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.i686-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
git-tree-sha1 = "a87422e6823768239a59638b30bafd4b1e5a6fef"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "1d6e0b9f06ee01c0e3f101c42abb206da97a0db9a8e0f86b03f5adc0615afd3c"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.powerpc64le-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "934238daa73ecb5b7e3cacda2b8f98d943d1c4ff"
os = "macos"

    [[ADOLC.download]]
    sha256 = "6ec3cd72b895bc6254d3baeb8c8d039cbc2c244b604aa23ce17f525644a6f9c7"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.x86_64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "cf05d495c9289cff19c9a2566a4f9a1c7176dc6f"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "30994e64bfd1dcd41856ab774aa9cf94bf21689c4cefc90517524959e948bce9"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.x86_64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "ce242b7338124baf5bd1a271f651d3f5235bf17b"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "9a6224b00a70a8a8981ca4d9bb356b8ad5ccf4981c40571ee6b76ed354110cfe"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.x86_64-linux-musl.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "c62fa73208a7cee0590e033a9540897a4bc6b672"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "8c0b0ad6318069b1fe124853c3c11be4bc12341f9507a9c90f30e6cd0fa387aa"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.x86_64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "40060e64d2679dbe8deeb51cca0369abaa3a3e42"
os = "windows"

    [[ADOLC.download]]
    sha256 = "ffb0894cfb3d810ae80703281059c7f2941d805e1f28b65cb859c4469a4f6369"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.7+0/ADOLC.v0.0.7.x86_64-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "cbacb8cc5ee190adc86eac2e6154b3c4745da3c4"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "7f10aeeae72e0ce8389b2975b12c84a7aff13ff06d15906810e3e8de4c610a6a"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "12681b9a5c302554f822bb1e855ea257df8e7934"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "6d021194c08f461651a8e14b3cddbd0de522dfb120bac7f4567799c2ab2ddb46"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "9162f24e52722c8601daa600b852100893d86b2b"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "c2ee907013ea016ba18478114f407e470b6015625c40f13aaf12aaeabd6c30dd"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.i686-w64-mingw32-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "e3b891751ef2432620b16d0aa28f36f82ce3f844"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "616ef85f57d92bbc9943b1f4a5a4b8d71b48a2439b97cd2f31f0d786f49067b2"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.i686-w64-mingw32-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "e72a983d33a962b04f45c6a4a2142171db326fbd"
julia_version = "1.10.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "fff3865298249523d7d472b79e75dfe021fb804d33b682348ecb3c7e664f9635"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "20038ff970ef9f84ae98dcf2f58cbd35edf96348"
julia_version = "1.9.0"
os = "macos"

    [[ADOLC.download]]
    sha256 = "0b79acb479bca8eec92b0ed82e44331bbbb46c50d2bce017ef9aeae6efc34aab"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "7190c98be08bbb1384bc1537b043a0d41e75c14b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "55f6b24f8bf0685bca5d180ab834fb86465c324d1c849edc6cda94b3636f9a84"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "c9aa4358579f2580e82b705665b72a8ac45d21b2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "7e83bce95f2d77251758e5b429d89cef3b55b98deb4027a322d311c86f6547e3"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "379add62364d7e350af6a599bcd08c3cd1b5e944"
julia_version = "1.10.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "eb631136aec8afac67a6357329aea4c198557e8d5a135ef17a4f1c5485a38635"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-w64-mingw32-julia_version+1.10.0.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "c80fd1528c720841e6e291ed92f2613d29476d93"
julia_version = "1.9.0"
os = "windows"

    [[ADOLC.download]]
    sha256 = "87eede8c4b31cd22cb204021dd759c60e8ee75f7a12de0dc3fcce369e93647b9"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.8+0/ADOLC.v0.0.8.x86_64-w64-mingw32-julia_version+1.9.0.tar.gz"
