[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "b5ffaa29bfa8e99dedf812ecbd2b97f680381145"
os = "macos"

    [[ADOLC.download]]
    sha256 = "506345f4d7c491ba56c7e72e0cc9877c9427cdeb2b36cebdfd5656e8e0cca9e9"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "aarch64"
git-tree-sha1 = "8e6c9e397c01dac2cd6dde16a4dd652ba832a88d"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "068482b897eae84f22ff3599b7cdfa93adff51348c15c3bee362054c90a8b95b"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.aarch64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c17e166f0f6ee5246f95922a5bc6db3be069259"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "e298d00d71a7a4a0521f9c1b7a11de3be22f70ec31947a3fc34e5ba3b4ae3ac9"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43735d9b130be79f6e884e38c7f131f63f55f9bb"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "b0a2438356fcb3c053fe5ad7f2ded61fa8c4291e1e483b40219b01a5ad9534db"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "c6c94301b88302a49a6fa12f5f304e70450faf4b"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "bc3a12688c464b13b343670c7ed6645413299146a7cf0f100fc649d3128b7d15"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-linux-gnu.tar.gz"
[[ADOLC]]
arch = "i686"
git-tree-sha1 = "5823e6cd0de2c4f61f4061e0cdc1d7555fc5b8b7"
os = "windows"

    [[ADOLC.download]]
    sha256 = "d2cc00d5c5d90cf91e1bd9a1307aceca7fd773bd2982f59ab7dd739b5063d5dd"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.i686-w64-mingw32.tar.gz"
[[ADOLC]]
arch = "powerpc64le"
git-tree-sha1 = "84683df8811b3dc9ccc8789b5fc5c38f74d60c8f"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "1bcb9ac36e5434e519ea0321600008736ee013348113b79a46592ee3c153e8c5"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "d9be05e5dca0b409feefbcfcca79cb6503826400"
os = "macos"

    [[ADOLC.download]]
    sha256 = "560b587e8890330b101a19397599e902859cdc797add7329c8b8d0ec4da99431"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-apple-darwin.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "c9206c62f7e7daca6428a403acc0c384e727521b"
libc = "glibc"
os = "linux"

    [[ADOLC.download]]
    sha256 = "acbb24f1c5bff55e9dee06d880e1496f8e58ef80e32603b2a5ce147ed04e7e3d"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-gnu.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "a9fdc65d8c0f6b7cde252f285c674e95e19462d4"
libc = "musl"
os = "linux"

    [[ADOLC.download]]
    sha256 = "6b056ad7c25cf774d8cba68357a9d2748b6f18ba805c4aa2675e432640d7631a"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-linux-musl.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "9db9ebaa014d17bb44fe88315296aa26ff0c28e9"
os = "freebsd"

    [[ADOLC.download]]
    sha256 = "acb24d2b3900c70e08a28e1d0f2a96de6ec3512e41602854b73d4bea9d9f0851"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[ADOLC]]
arch = "x86_64"
git-tree-sha1 = "0d5776ce84dbe607246d8de667deab9352359d2b"
os = "windows"

    [[ADOLC.download]]
    sha256 = "4836196ab7e6265df19db8e00cf672d101a48d52e92fd092d7586ab3a9ad81c1"
    url = "https://github.com/TimSiebert1/ADOLC_jll.jl/releases/download/ADOLC-v0.0.1+0/ADOLC.v0.0.1.x86_64-w64-mingw32.tar.gz"
