# Autogenerated wrapper script for ADOLC_jll for aarch64-apple-darwin-julia_version+1.9.0
export libadolc_wrap

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("ADOLC")
JLLWrappers.@declare_library_product(libadolc_wrap, "@rpath/libadolc_wrap.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libadolc_wrap,
        "lib/libadolc_wrap.0.0.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
