# Autogenerated wrapper script for ADOLC_jll for aarch64-apple-darwin
export adolc_wrap

using libcxxwrap_julia_jll
using libjulia_jll
JLLWrappers.@generate_wrapper_header("ADOLC")
JLLWrappers.@declare_library_product(adolc_wrap, "@rpath/libadolc_wrap.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, libjulia_jll)
    JLLWrappers.@init_library_product(
        adolc_wrap,
        "lib64/libadolc_wrap.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
