# Autogenerated wrapper script for ADOLC_jll for x86_64-w64-mingw32
export adolc_interface_lib, adolc_lib

JLLWrappers.@generate_wrapper_header("ADOLC")
JLLWrappers.@declare_library_product(adolc_interface_lib, "libADOLCInterface.dll")
JLLWrappers.@declare_library_product(adolc_lib, "libadolc.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        adolc_interface_lib,
        "bin\\libADOLCInterface.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        adolc_lib,
        "bin\\libadolc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
